// @ts-check
"use strict";

/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    //     `2` -> means -> error (refuses to commit)
    // `never` -> The scope is never allowed to be empty
    "scope-empty": [2, "never"],

    // Header (type + scope + subject) "always" -> must not exceed 72 characters
    "header-max-length": [2, "always", 72],

    // Each line in the commit body "always" -> must not exceed 72 characters
    "body-max-line-length": [2, "always", 72],

    "type-enum": [
      2,
      "always",
      ["feat", "fix", "perf", "style", "refactor", "docs", "test", "chore", "build", "ci", "revert"],
    ],

    // Restrict the scope to this exact list. This array is the single source
    // of truth for accepted scopes. When you add, remove, or rename a scope
    // here, remember to keep the related internal reference in sync.
    "scope-enum": [
      2,
      "always",
      [
        "activate",
        "ai",
        "ai-check-status",
        "ai-explain",
        "ai-factory",
        "ai-generate",
        "ai-settings",
        "anthropic",
        "auto-variables",
        "categories",
        "changelog",
        "cliff",
        "code-of-conduct",
        "codebase-map",
        "cohere",
        "command-form",
        "commands",
        "commitlint",
        "connection-watchdog",
        "contributing",
        "data-safety",
        "deepseek",
        "deps",
        "deps-dev",
        "drag-drop",
        "edit-command",
        "enum-manager",
        "eslint",
        "extension",
        "faqs",
        "favorites",
        "gemini",
        "gitignore",
        "globals",
        "groq",
        "handlers",
        "help-links",
        "highlight",
        "husky",
        "icon",
        "icons",
        "images",
        "issue-templates",
        "license",
        "logger",
        "main",
        "manage-tab",
        "markdown-parser",
        "media",
        "messages",
        "mistral",
        "modals",
        "normalize",
        "notice",
        "openai",
        "packaging",
        "pr-template",
        "prettier",
        "providers-config",
        "readme",
        "recent",
        "release",
        "render",
        "run-confirm",
        "schemas",
        "scripts",
        "security",
        "settings",
        "state",
        "stepfun",
        "storage",
        "styles",
        "system-instruction",
        "terminal",
        "testing",
        "tooltip",
        "ui",
        "ui-state",
        "utils",
        "variables",
        "vscodeignore",
        "webview",
        "workflows",
      ],
    ],
  },
};
